spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.103:64000/cinema
    username: pg
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect